# File: .github/workflows/update-universities.yml
name: Update University Data

on:
  schedule:
    - cron: '0 3 * * 0'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-universities:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - run: pip install requests beautifulsoup4 lxml

    - run: python universities_scraper.py

    - run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add universities.json universities-name.json
        git diff --staged --quiet || git commit -m "🤖 Update data"
        git push
