# File: .github/workflows/update-universities.yml
name: Update University Data

on:
  schedule:
    - cron: '0 3 * * 0'  # Every Sunday at 3 AM UTC
  workflow_dispatch:      # Manual trigger

jobs:
  update-universities:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 lxml

    - name: Run university scraper
      run: python universities_scraper.py

    - name: Check if files were created
      run: |
        echo "Checking for generated files:"
        ls -la *.json || echo "No JSON files found yet"

    - name: Configure Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Commit and push changes
      run: |
        # Add the generated JSON files
        git add universities.json universities-name.json
        
        # Check if there are changes to commit
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "🤖 Auto-update university data [$(date +'%Y-%m-%d')]"
          git push
        fi
